# This is a config that other rom-rb repositories use

sources:
  - repo: rom-rb/template-gem
    sync:
      - "!.github/workflows/ci.yml.erb"
      - "!README.md.erb"
      - ".action_hero.yml.erb"
      - ".devtools/templates/*.sync:${{dir}}/${{name}}"
      - ".github/**/*.*"
      - "spec/*"
      - ".*"
      - "*"
  - repo: action-hero/workflows
    sync:
      - ".github/workflows/*.yml"
