require 'active_record'

require 'data_mapper/engine'
require 'data_mapper/engine/arel/engine'
require 'data_mapper/engine/arel/gateway'
require 'data_mapper/engine/arel/node'
require 'data_mapper/engine/arel/edge'
require 'data_mapper/engine/arel/aliases'
require 'data_mapper/engine/arel/aliases/unary'
require 'data_mapper/engine/arel/aliases/binary'
