require 'data_mapper/engine'
require 'data_mapper/engine/veritas/engine'
require 'data_mapper/engine/veritas/node'
require 'data_mapper/engine/veritas/edge'
require 'data_mapper/engine/veritas/aliases'
require 'data_mapper/engine/veritas/aliases/unary'
require 'data_mapper/engine/veritas/aliases/binary'
